source 'https://rubygems.org'

ruby '~> 3.2.0'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 6.0'
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug'
  gem 'rspec-rails'
end

group :development do
  gem 'web-console'
end
